[package]
name = "minedmap-resource"
version = "0.9.0"
description = "Data describing Minecraft biomes and block types"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
bincode = "2.0.1"
enumflags2 = "0.7.7"
glam = "0.30.0"
